# Generated by Django 3.1.7 on 2021-03-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20210304_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='ture',
            name='price',
            field=models.FloatField(default=2.0),
        ),
    ]
