# Generated by Django 3.1.7 on 2021-03-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20210304_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ture',
            old_name='rate',
            new_name='km_rate',
        ),
    ]
