# Generated by Django 3.1.7 on 2021-03-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20210304_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indbetaling',
            name='description',
        ),
    ]
