# Generated by Django 3.1.7 on 2021-03-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_auto_20210304_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ture',
            options={'verbose_name': 'Tur'},
        ),
    ]
