# Generated by Django 3.1.7 on 2021-03-04 20:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0009_auto_20210304_2028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ture',
            new_name='Tur',
        ),
        migrations.AlterModelOptions(
            name='tur',
            options={'verbose_name_plural': 'Ture'},
        ),
    ]
