# Generated by Django 3.1.7 on 2021-03-04 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_auto_20210304_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tur',
            old_name='km_count',
            new_name='odometer',
        ),
    ]
