# Generated by Django 3.1.7 on 2021-03-04 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_tur_km_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tur',
            old_name='km_count',
            new_name='delta_km',
        ),
    ]
