# Generated by Django 3.1.7 on 2021-03-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_auto_20210304_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='tur',
            name='tur_price',
            field=models.FloatField(default=0.0),
        ),
    ]
