# Generated by Django 3.1.7 on 2021-03-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_udbetaling'),
    ]

    operations = [
        migrations.AddField(
            model_name='udbetaling',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
