# Generated by Django 3.1.7 on 2021-03-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_udbetaling_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='indskud',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
